### ISSUE TITLE
XGBoostError: [17:50:38] ../src/data/data.cc:945: Check failed: valid: Input data contains `inf` or `nan`

### ISSUE THREAD

**Issue by Andrew05200** [LogicJake/tianchi-loan-default-prediction-top11#1]
您好，非常感谢您的分享，我在复现这个项目过程中，执行xgb.ipynb 时遇到如下错误，xgboost不是默认可以处理缺失值吗？这个错误比较疑惑，希望可以得到您的解答。

`
Fold_1 Training ================================

---------------------------------------------------------------------------
XGBoostError                              Traceback (most recent call last)
<ipython-input-20-8f14f87d12bb> in <module>
     35                           verbose=100,
     36                           eval_metric='auc',
---> 37                           early_stopping_rounds=50)
     38 
     39     pred_val = xgb_model.predict_proba(X_val)[:, 1]

~/anaconda3/envs/pxwang/lib/python3.7/site-packages/xgboost/core.py in inner_f(*args, **kwargs)
    434         for k, arg in zip(sig.parameters, args):
    435             kwargs[k] = arg
--> 436         return f(**kwargs)
    437 
    438     return inner_f

~/anaconda3/envs/pxwang/lib/python3.7/site-packages/xgboost/sklearn.py in fit(self, X, y, sample_weight, base_margin, eval_set, eval_metric, early_stopping_rounds, verbose, xgb_model, sample_weight_eval_set, base_margin_eval_set, feature_weights, callbacks)
   1171             eval_qid=None,
   1172             create_dmatrix=lambda **kwargs: DMatrix(nthread=self.n_jobs, **kwargs),
-> 1173             label_transform=label_transform,
   1174         )
   1175 

~/anaconda3/envs/pxwang/lib/python3.7/site-packages/xgboost/sklearn.py in _wrap_evaluation_matrices(missing, X, y, group, qid, sample_weight, base_margin, feature_weights, eval_set, sample_weight_eval_set, base_margin_eval_set, eval_group, eval_qid, create_dmatrix, label_transform)
    242         base_margin=base_margin,
    243         feature_weights=feature_weights,
--> 244         missing=missing,
    245     )
    246 

~/anaconda3/envs/pxwang/lib/python3.7/site-packages/xgboost/sklearn.py in <lambda>(**kwargs)
   1170             eval_group=None,
   1171             eval_qid=None,
-> 1172             create_dmatrix=lambda **kwargs: DMatrix(nthread=self.n_jobs, **kwargs),
   1173             label_transform=label_transform,
   1174         )

~/anaconda3/envs/pxwang/lib/python3.7/site-packages/xgboost/core.py in inner_f(*args, **kwargs)
    434         for k, arg in zip(sig.parameters, args):
    435             kwargs[k] = arg
--> 436         return f(**kwargs)
    437 
    438     return inner_f

~/anaconda3/envs/pxwang/lib/python3.7/site-packages/xgboost/core.py in __init__(self, data, label, weight, base_margin, missing, silent, feature_names, feature_types, nthread, group, qid, label_lower_bound, label_upper_bound, feature_weights, enable_categorical)
    545             feature_names=feature_names,
    546             feature_types=feature_types,
--> 547             enable_categorical=enable_categorical,
    548         )
    549         assert handle is not None

~/anaconda3/envs/pxwang/lib/python3.7/site-packages/xgboost/data.py in dispatch_data_backend(data, missing, threads, feature_names, feature_types, enable_categorical)
    572     if _is_pandas_df(data):
    573         return _from_pandas_df(data, enable_categorical, missing, threads,
--> 574                                feature_names, feature_types)
    575     if _is_pandas_series(data):
    576         return _from_pandas_series(data, missing, threads, feature_names,

~/anaconda3/envs/pxwang/lib/python3.7/site-packages/xgboost/data.py in _from_pandas_df(data, enable_categorical, missing, nthread, feature_names, feature_types)
    259         data, enable_categorical, feature_names, feature_types)
    260     return _from_numpy_array(data, missing, nthread, feature_names,
--> 261                              feature_types)
    262 
    263 

~/anaconda3/envs/pxwang/lib/python3.7/site-packages/xgboost/data.py in _from_numpy_array(data, missing, nthread, feature_names, feature_types)
    167         ctypes.c_float(missing),
    168         ctypes.byref(handle),
--> 169         ctypes.c_int(nthread)))
    170     return handle, feature_names, feature_types
    171 

~/anaconda3/envs/pxwang/lib/python3.7/site-packages/xgboost/core.py in _check_call(ret)
    208     """
    209     if ret != 0:
--> 210         raise XGBoostError(py_str(_LIB.XGBGetLastError()))
    211 
    212 

XGBoostError: [22:08:48] ../src/data/data.cc:945: Check failed: valid: Input data contains `inf` or `nan`
Stack trace:
  [bt] (0) /root/anaconda3/envs/pxwang/lib/python3.7/site-packages/xgboost/lib/libxgboost.so(+0x9133f) [0x7fcb8c32733f]
  [bt] (1) /root/anaconda3/envs/pxwang/lib/python3.7/site-packages/xgboost/lib/libxgboost.so(+0x14e930) [0x7fcb8c3e4930]
  [bt] (2) /root/anaconda3/envs/pxwang/lib/python3.7/site-packages/xgboost/lib/libxgboost.so(+0x15f8ff) [0x7fcb8c3f58ff]
  [bt] (3) /root/anaconda3/envs/pxwang/lib/python3.7/site-packages/xgboost/lib/libxgboost.so(+0x156cf5) [0x7fcb8c3eccf5]
  [bt] (4) /root/anaconda3/envs/pxwang/lib/python3.7/site-packages/xgboost/lib/libxgboost.so(XGDMatrixCreateFromMat_omp+0x7c) [0x7fcb8c31f04c]
  [bt] (5) /root/anaconda3/envs/pxwang/lib/python3.7/lib-dynload/../../libffi.so.7(+0x69dd) [0x7fcbe67af9dd]
  [bt] (6) /root/anaconda3/envs/pxwang/lib/python3.7/lib-dynload/../../libffi.so.7(+0x6067) [0x7fcbe67af067]
  [bt] (7) /root/anaconda3/envs/pxwang/lib/python3.7/lib-dynload/_ctypes.cpython-37m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7fcbe553127e]
  [bt] (8) /root/anaconda3/envs/pxwang/lib/python3.7/lib-dynload/_ctypes.cpython-37m-x86_64-linux-gnu.so(+0x12cb4) [0x7fcbe5531cb4]`

**Comment by Andrew05200** [comment]
已解决，把xgboost 从1.4.2 改为1.3.2即可

**Comment by liningbo** [comment]
@Andrew05200  why change xgboost to 1.3.2 can solve the problem about inf or nan? I had also met the problem and change xgboost from 1.5.0 to 1.3.2 ,then solve it.

**Comment by GforikeW** [comment]
> 已解决，把xgboost 从1.4.2 改为1.3.2即可

怎么改，好像3.9.7不能下载1.3.2，能分享一下吗
